name: CI

on:
  push:
    branches: [ docusaurus-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'doc'
          target-directory: 'docs'
          destination-github-username: 'dt3264'
          destination-repository-name: 'huronos-auto-website'
          user-email: cernadaniel32@gmail.com
          target-branch: main